name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: artifacts
          path: C:\Users\c.bhavya\Desktop\HDFC PROJ\java-trainning\Bhavya-Java\server\target\server.jar

      - name: Deploy to Tomcat
        run: |
          TOMCAT_URL="http://localhost:8080"
          TOMCAT_USERNAME="tomcat-users.xml"
          TOMCAT_PASSWORD="varshu"
          WAR_FILE_PATH="artifacts/my-java-app.zip"  # Update the path if necessary

          # Deploy using curl command (replace [WAR_FILENAME] with your war file name)
          curl -T $WAR_FILE_PATH "$TOMCAT_URL/manager/text/deploy?path=/myapp&update=true" --user "$TOMCAT_USERNAME:$TOMCAT_PASSWORD"
