name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    env:
      GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      GH_HOSTNAME: ${{ secrets.GH_HOSTNAME }}
      TOMCAT_USERNAME: ${{ secrets.TOMCAT_USERNAME }}
      TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        run: |
          echo "JAVA_HOME=C:\Program Files\Java\jdk-11" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Download artifact
        run: |
          gh release download v4.4.3 -p "my-java-app.zip" --repo cbhavya09/cicd

      - name: Extract artifact
        run: Expand-Archive -Path "C:\Users\c.bhavya\Desktop\demo\demo\actions-runner\_work\cicd\cicd\my-java-app.zip" -DestinationPath "C:\Users\c.bhavya\Desktop\cicd\my-java-app"

      - name: Copy JAR file to Tomcat webapps
        run: Copy-Item -Path "C:\Users\c.bhavya\Desktop\cicd\my-java-app\helloworld-2.6.jar" -Destination "C:\apache-tomcat-10.1.13\webapps"

      - name: Check if Tomcat is running
        run: |
          $tomcatRunning = Test-NetConnection -ComputerName "localhost" -Port 8080
          if ($tomcatRunning.TcpTestSucceeded -eq $true) { exit 0 } else { exit 1 }

      - name: Wait for Tomcat to start
        run: Start-Sleep -s 60  # Wait for Tomcat to fully start (adjust the delay as needed)

      - name: Verify deployment
        run: |
          # Verify that the application is accessible
          $response = Invoke-WebRequest -Uri "http://localhost:8080/webapps/helloworld-2.6" -Method Get
          if ($response.StatusCode -eq 200) {
              Write-Host "Deployment successful."
          } else {
              Write-Host "Deployment failed with status code $($response.StatusCode)."                
          }

