name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifacts
          path: C:/Users/c.bhavya/Desktop/cicd/target/*.war

      - name: Deploy to Tomcat
        run: |
          chmod +x deploy-to-tomcat.sh
          ./deploy-to-tomcat.sh
