name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    env:
      GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      GH_HOSTNAME: ${{ vars.GH_HOSTNAME}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        run: |
          echo "JAVA_HOME=C:\Program Files\Java\jdk-11" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV
          
      - name: Download artifact
        run: |
          gh release download v6.0.0 -p "my-java-app.zip" --repo cbhavya09/JAVA-APPLICATION
      
      - name: Deploy to Tomcat
        run: |
          TOMCAT_URL="http://localhost:8080"
          TOMCAT_USERNAME="deploy"
          TOMCAT_PASSWORD="varshu"
          $WAR_FILE_PATH="artifacts/my-java-app.zip"

          # Deploy using curl command
          curl -T $WAR_FILE_PATH "$($TOMCAT_URL)/manager/text/deploy?path=/myapp&update=true" --user "$($TOMCAT_USERNAME):$($TOMCAT_PASSWORD)"