name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TOMCAT_USERNAME: ${{ secrets.TOMCAT_USERNAME }}
      TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
      TOMCAT_HOSTNAME: localhost  # Update with your Tomcat hostname
      TOMCAT_PORT: 8080          # Update with your Tomcat port
      ARTIFACT_NAME: myapp.war    # Update with your artifact name

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        run: |
          echo "JAVA_HOME=C:\Program Files\Java\jdk-11" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Download artifact
        run: |
          curl -LJO "https://github.com/cbhavya09/cicd/releases/download/v6.0.0/${{ env.ARTIFACT_NAME }}"
          mv "${{ env.ARTIFACT_NAME }}" "${{ github.workspace }}/${{ env.ARTIFACT_NAME }}"
        
      - name: Set up Tomcat
        run: |
          sudo apt-get update
          sudo apt-get install -y tomcat9  # Install Tomcat (adjust for your version)
          sudo systemctl start tomcat9     # Start Tomcat
          sudo systemctl enable tomcat9   # Enable Tomcat to start on boot

      - name: Wait for Tomcat to start
        run: sleep 10  # Adjust if needed to wait for Tomcat to start properly

      - name: Deploy WAR file to Tomcat
        run: |
          # Extract the base name of the artifact (removes ".war" extension)
          ARTIFACT_BASENAME=$(basename "${{ env.ARTIFACT_NAME }}" .war)
          
          curl -v -u "${{ env.TOMCAT_USERNAME }}:${{ env.TOMCAT_PASSWORD }}" \
            -T "${{ github.workspace }}/${{ env.ARTIFACT_NAME }}" \
            "http://${{ env.TOMCAT_HOSTNAME }}:${{ env.TOMCAT_PORT }}/manager/text/deploy?path=/${ARTIFACT_BASENAME}&update=true"

      - name: Verify deployment
        run: |
          sleep 10  # Adjust if needed to wait for deployment to complete
          response_code=$(curl -s -o /dev/null -w "%{http_code}" \
            "http://${{ env.TOMCAT_HOSTNAME }}:${{ env.TOMCAT_PORT }}/${{ env.ARTIFACT_NAME }}/")

          if [ "$response_code" == "200" ]; then
            echo "Deployment successful."
          else
            echo "Deployment failed with HTTP status code $response_code."
            exit 1
          fi
