name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    env:
      GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      GH_HOSTNAME: ${{ secrets.GH_HOSTNAME }}
      TOMCAT_USERNAME: ${{ secrets.TOMCAT_USERNAME }}
      TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        run: |
          echo "JAVA_HOME=C:\Program Files\Java\jdk-11" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV
      - name: Download artifact
        run: |
          gh release download v6.1.1 -p "mywebapp.zip" --repo cbhavya09/cicd

      - name: Extract artifact
        run: Expand-Archive -Path "C:\Users\c.bhavya\Desktop\demo\demo\actions-runner\_work\cicd\cicd\mywebapp.zip" -DestinationPath "C:\apache-tomcat-10.1.13\webapps"

      - name: Copy WAR file to Tomcat webapps
        run: Copy-Item -Path "C:\Users\c.bhavya\Desktop\cicd\cicd\target\myapp.war" -Destination "C:\apache-tomcat-10.1.13\webapps"

      - name: Set up Tomcat
        run: |
          $env:TOMCAT_HOME = "C:\apache-tomcat-10.1.13"
          $env:PATH = "$env:PATH;$env:TOMCAT_HOME\bin"
      - name: Check if Tomcat is running
        run: |
          $tomcatRunning = Test-NetConnection -ComputerName "localhost" -Port 8080
          if ($tomcatRunning.TcpTestSucceeded -eq $true) { exit 0 } else { exit 1 }
          
      - name: Deploy WAR to Tomcat
        run: |
          # Define the Tomcat webapps directory and WAR file path
          $TOMCAT_WEBAPPS_DIR = "C:\apache-tomcat-10.1.13\webapps"  # Path to the Tomcat webapps directory
          $WAR_FILE_PATH = "C:\apache-tomcat-10.1.13\webapps\myapp.war"  # Path to your WAR file
          # No need to copy the WAR file again; it's already in the webapps directory
          Write-Host "Deployment successful."