name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TOMCAT_USERNAME: ${{ secrets.TOMCAT_USERNAME }}
      TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
      TOMCAT_HOSTNAME: localhost  # Update with your Tomcat hostname
      TOMCAT_PORT: 8080          # Update with your Tomcat port
      ARTIFACT_NAME: myapp.war    # Update with your artifact name

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        run: |
          echo "JAVA_HOME=C:\Program Files\Java\jdk-11" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Download and move artifact
        run: |
            curl -LJO "https://github.com/cbhavya09/cicd/releases/download/v6.0.0/myapp.war"
            if [ ! -f "${{ github.workspace }}/${{ env.ARTIFACT_NAME }}" ]; then
              mv "${{ env.ARTIFACT_NAME }}" "${{ github.workspace }}/${{ env.ARTIFACT_NAME }}"
            else
              echo "Artifact file already exists in the workspace directory."
            fi
        
      - name: Set up Tomcat
        run: |
              $env:TOMCAT_HOME = "C:\apache-tomcat-10.1.13"
              $env:PATH = "$env:PATH;$env:TOMCAT_HOME\bin"
          
      - name: Check if Tomcat is running
        run: |
            $tomcatRunning = Test-NetConnection -ComputerName "localhost" -Port 8080
            if ($tomcatRunning.TcpTestSucceeded -eq $true) { exit 0 } else { exit 1 }
          
      - name: Deploy file to Tomcat
        run: |
              # Define the Tomcat webapps directory and WAR file path
              $TOMCAT_WEBAPPS_DIR = "C:\apache-tomcat-10.1.13\webapps"  # Path to the Tomcat webapps directory
              $WAR_FILE_PATH = "$TOMCAT_WEBAPPS_DIR\mywebapp.war"  # Path to your WAR file
              
              # No need to copy the WAR file again; it's already in the webapps directory
              Write-Host "Deployment successful."
          