name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        run: |
          echo "JAVA_HOME=C:\Program Files\Java\jdk-11" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV
    
      - name: Download Apache Maven
        run: |
            wget -nc "https://apache.org/dyn/mirrors/mirrors.cgi?action=download&filename=maven/maven-3/3.8.3/binaries/apache-maven-3.8.3-bin.tar.gz" -O maven.tar.gz
            tar xzf maven.tar.gz
            echo "export PATH=\$PATH:$(pwd)/apache-maven-3.8.3/bin" >> $GITHUB_ENV
        shell: bash
        
      - name: Set up Maven
        run: |
          export PATH="$PATH:/c/apache-maven-3.9.0/bin"
        shell: bash
      
      - name: List files in target directory
        run: ls -R target
      
      - name: Debug directory contents
        run: echo "Directory contents: $(ls -R target)"
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: target/*.war
        if-no-files-found: warn
      