name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        run: |
          echo "JAVA_HOME=C:\Program Files\Java\jdk-11" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV
    
      - name: Build with Maven
        run: C:\apache-maven-3.9.2\bin\mvn clean install

      - name: Package the artifact
        run: |
          $outputPath = "myapp.zip"
          $sourcePath = "C:\Users\c.bhavya\Desktop\cicd\cicd\target\myapp-1.war"
          Compress-Archive -Path $sourcePath -DestinationPath $outputPath
          
      - name: Authenticate with GitHub
        run: |
          echo "machine github.com login ${{ secrets.MY_GITHUB_USERNAME }} password ${{ secrets.MY_GITHUB_TOKEN }}" > ~/.netrc
      
    
      - name: Publish the artifact to GitHub release
        run: |
          gh release create v6.4.1 myapp.zip
        env:
          GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}