name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        run: |
          echo "JAVA_HOME=C:\Program Files\Java\jdk-11" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV
    
      - name: Build with Maven
        run: C:\apache-maven-3.9.2\bin\mvn clean install

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v2
        with:
          name: myapp
          path: target/myapp.war

      - name: Authenticate with GitHub
        run: |
          echo "machine github.com login ${{ secrets.MY_GITHUB_USERNAME }} password ${{ secrets.MY_GITHUB_TOKEN }}" > ~/.netrc

      - name: Create GitHub Release
        run: |
          gh release create v6.0.0 target/myapp.war --title "MyApp v1.0.0" --notes "Release notes for v1.0.0"
        env:
          GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
